### PR TITLE
Copy 'mising -e' error from compile to sync

### PR DESCRIPTION
**Pull request by pquentin**
Not sure if this is the best way to do it? But the `AttributeError` that I was getting before was not really informative. Thanks!

### CODE REVIEW

**Comment by frgtn** [comment]
:+1: I think it's a good idea.

**Comment by nvie** [comment]
Thanks!

**Comment by nvie** [comment]
This has been released as part of pip-tools==1.1.5 just now. Thanks for contributing!

**Comment by pquentin** [comment]
Thank you!

**Pull request merged**
