### PR TITLE
Mark appnope as unsafe package

### PR DESCRIPTION
**Pull request by achauve**

### CODE REVIEW

**Comment by nvie** [comment]
At the very least, I'll need to have some motivation for this.

**Comment by achauve** [comment]
Yes sorry I created an issue with some context: see #277 

Appnope is required by ipython only on OSX, so when you develop on OSX and then deploy on linux using pip-tools generated requirements.txt breaks deployment.

**Comment by achauve** [comment]
@nvie What do you think?

**Comment by nvie** [comment]
We have now concluded that appnope itself is not an issue (https://github.com/nvie/pip-tools/issues/285#issuecomment-169847863), so I'm closing this one.

**Pull request closed without merging**
