### PR TITLE
future: fix tests

### PR DESCRIPTION
**Pull request by blueyed**
This fixes three test failures/errors, and adds tests for OutputWriter (for the moved annotation code).

(this is included in #169)

### CODE REVIEW

**Comment by blueyed** [comment]
@nvie 
Without this being merged the Travis build results for new PRs are not that useful (because they will all fail).

Therefore, please merge / review this.

**Comment by blueyed** [comment]
@nvie 
Please re-open?!

**Comment by nvie** [comment]
Sorry 'bout that — reopened.

**Comment by nvie** [comment]
Thanks a lot!

**Comment by nvie** [comment]
This is now merged into master, so I'll manually close this PR that targets the `future` branch.

**Pull request closed without merging**
